Solbakken/Models/Album.cs
using System;
using System.Collections.ObjectModel;
using CodeFirstMembershipSharp;

namespace Solbakken.Models
{
    public class Album
    {
        public int Id { get; set; }
        public string Navn { get; set; }
        public DateTime Opprettet { get; set; }
        public User OpprettetAv { get; set; }
        public virtual Collection<Bilde> Bilder { get; set; }
    }
}

Solbakken/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Solbakken.Models;
using CodeFirstMembershipSharp;

namespace Solbakken.Controllers
{
    [Authorize]
    public class AlbumController : Controller
    {
        private readonly DataContext _db = new DataContext();

        //
        // GET: /Album/

        public ActionResult Index()
        {
            var user = _db.Users.FirstOrDefault(x => x.Username == User.Identity.Name);
            return View(_db.Albums.Where(x => x.OpprettetAv.UserId == user.UserId).ToList());
        }

        //
        // GET: /Album/Details/5

        public ActionResult Details(int id = 0)
        {
            Album album = _db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        //
        // GET: /Album/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Album/Create

        [HttpPost]
        public ActionResult Create(Album album)
        {
            if (ModelState.IsValid)
            {
                album.Opprettet = DateTime.Now;
                var user = _db.Users.FirstOrDefault(x => x.Username == User.Identity.Name);
                album.OpprettetAv = user;
                _db.Albums.Add(album);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(album);
        }

        //
        // GET: /Album/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Album album = _db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        //
        // POST: /Album/Edit/5

        [HttpPost]
        public ActionResult Edit(Album album)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(album).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(album);
        }

        //
        // GET: /Album/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Album album = _db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        //
        // POST: /Album/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Album album = _db.Albums.Find(id);
            _db.Albums.Remove(album);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Solbakken/Controllers/BildeController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using CodeFirstMembershipSharp;
using Solbakken.Models;
using Solbakken.Util;

namespace Solbakken.Controllers
{
    [Authorize]
    public class BildeController : Controller
    {
        private readonly DataContext _db = new DataContext();
        private readonly List<string> _incompatibleBrowsers = new List<string>{"Opera", "IE", "Safari"};
        public ActionResult LastOpp(string warning, string success)
        {
            ViewBag.AlbumId = new SelectList(_db.Albums, "Id", "Navn");
            ViewBag.Warning = warning;
            ViewBag.Success = success;
            return _incompatibleBrowsers.Contains(Request.Browser.Browser) ? View("LastOppEnkel") : View("Upload");
        }

        [HttpPost]
        public ActionResult LastOpp(int? albumId, string beskrivelse)
        {
            if(albumId == null)
            {
                return RedirectToAction("LastOpp", new {warning = "Du må velge et album"});
            }
            var image = Request.Files.Count > 0 ? Request.Files[0] : null;
            var imagesUploadedCounter = 0;
            if (image != null)
            {
                if(ImageUtil.AllowedImageTypes.Contains(image.ContentType))
                {
                    var im = Image.FromStream(image.InputStream);
                    var imageFormat = ImageUtil.GetImageFormat(image.ContentType);
                    var newImage = im.Resize(640, 480);
                    var thumbnail = im.Resize(100, 75);
                    var album = _db.Albums.Find(albumId) ?? _db.Albums.FirstOrDefault();
                    var user = _db.Users.FirstOrDefault(x => x.Username == User.Identity.Name);
                    if (album != null)
                    {
                        var bilde = new Bilde
                                        {
                                            AlbumId = album.Id,
                                            Beskrivelse = beskrivelse,
                                            Format = imageFormat.ToString(),
                                            BildeStream = ReadFully(newImage.ToStream(imageFormat)),
                                            Filnavn = image.FileName,
                                            LastetOppAvId = user.UserId,
                                            Navn = image.FileName,
                                            Thumbnail = ReadFully(thumbnail.ToStream(imageFormat))
                                        };
                        imagesUploadedCounter++;
                        _db.Bilder.Add(bilde);
                    }
                    _db.SaveChanges();
                }
            }
            return RedirectToAction("LastOpp", new {success = string.Format("{0} bilde{1} lastet opp.", imagesUploadedCounter, imagesUploadedCounter != 1 ? "r" : string.Empty)});
        }

        public JsonResult UploadMultiple(string filename, int albumId, string beskrivelse)
        {
            var count = Request.InputStream.Length;
            var pic = new byte[count];
            Request.InputStream.Read(pic, 0, (int)count);
            try
            {
                var im = Image.FromStream(new MemoryStream(pic));
                var extension = filename.Split('.').Last();
                var imageFormat = ImageUtil.GetImageFormatFromFileExtension(extension);
                var newImage = im.Resize(640, 480);
                var thumbnail = im.Resize(80, 60);
                var album = _db.Albums.Find(albumId) ?? _db.Albums.FirstOrDefault();
                var user = _db.Users.FirstOrDefault(x => x.Username == User.Identity.Name);
                if (album != null)
                {
                    var bilde = new Bilde
                                    {
                                        AlbumId = album.Id,
                                        Beskrivelse = beskrivelse,
                                        Format = imageFormat.ToString(),
                                        BildeStream = ReadFully(newImage.ToStream(imageFormat)),
                                        Filnavn = filename,
                                        LastetOppAvId = user.UserId,
                                        Navn = filename,
                                        Thumbnail = ReadFully(thumbnail.ToStream(imageFormat))
                                    };
                    _db.Bilder.Add(bilde);
                }
                _db.SaveChanges();
            }
            catch (Exception)
            {
                throw new FormatException("Wrong format on picture");
            }
            return Json(string.Format("La til {0}", filename));
        }

        public Guid GetUserId()
        {
            var user = _db.Users.FirstOrDefault(x => x.Username == User.Identity.Name);
            var userid = user != null ? user.UserId : Guid.NewGuid();
            return userid;
        }

        public JsonResult UploadJqueryMultiple(int? albumId)
        {
            if(albumId == null)
            {
                return null;
            }
            if(Request.Files.Count == 0)
            {
                var imageJsons = new List<JsonUploadResponse>();
                return Json(imageJsons, JsonRequestBehavior.AllowGet);
            }
            var count = Request.Files[0].InputStream.Length;
            var pic = new byte[count];
            var bilde = new Bilde();
            Request.InputStream.Read(pic, 0, (int)count);
            try
            {
                var file = Request.Files[0];
                if (file != null)
                {
                    var im = Image.FromStream(file.InputStream);
                    var extension = file.FileName.Split('.').Last();
                    var imageFormat = ImageUtil.GetImageFormatFromFileExtension(extension);
                    var newImage = im.Resize(800, 600);
                    var thumbnail = im.Resize(80, 60);
                    var user = _db.Users.FirstOrDefault(x => x.Username == User.Identity.Name);
                    bilde = new Bilde
                                {
                                    AlbumId = albumId,
                                    Beskrivelse = "",
                                    Format = imageFormat.ToString(),
                                    BildeStream = ReadFully(newImage.ToStream(imageFormat)),
                                    Filnavn = file.FileName,
                                    LastetOppAvId = user.UserId,
                                    Navn = file.FileName,
                                    Thumbnail = ReadFully(thumbnail.ToStream(imageFormat))
                                };
                    _db.Bilder.Add(bilde);
                    _db.SaveChanges();
                }
                
            }
            catch (Exception)
            {
                throw new FormatException("Wrong format on picture");
            }
            return
                Json(new[]
                         {
                             new JsonUploadResponse
                                 {
                                     delete_type = "DELETE",
                                     delete_url = "/Bilde/SlettBekreftet/" + bilde.Id,
                                     name = bilde.Navn,
                                     size = bilde.BildeStream.Count(),
                                     thumbnail_url = "/Home/GetThumbnail/" + bilde.Id,
                                     url = "/Home/GetImage/" + bilde.Id
                                 }
                         });
        }

        public ActionResult Upload(string warning, string success)
        {
            ViewBag.AlbumId = new SelectList(_db.Albums, "Id", "Navn");
            ViewBag.Warning = warning;
            ViewBag.Success = success;
            return View();
        }

        public static byte[] ReadFully(Stream input)
        {
            var buffer = new byte[16 * 1024 * 1024];
            using (var ms = new MemoryStream())
            {
                int read;
                while ((read = input.Read(buffer, 0, buffer.Length)) > 0)
                {
                    ms.Write(buffer, 0, read);
                }
                return ms.ToArray();
            }
        }

        public JsonResult SlettJson()
        {
            var skip = GetReferredSkip();
            var userId = GetUserId();
            var bilder = _db.Bilder.Where(x => x.LastetOppAvId == userId).OrderBy(x => x.Id).Skip(skip).Take(50).ToList();
            var jsonBilder = bilder.Select(bilde => new JsonUploadResponse
                                                        {
                                                            delete_type = "DELETE",
                                                            delete_url = "/Bilde/SlettBekreftet/" + bilde.Id,
                                                            name = bilde.Navn,
                                                            size = bilde.BildeStream.Count(),
                                                            thumbnail_url = "/Home/GetThumbnail/" + bilde.Id,
                                                            url = "/Home/GetImage/" + bilde.Id
                                                        });
            return Json(jsonBilder, JsonRequestBehavior.AllowGet);
        }

        private int GetReferredSkip()
        {
            var skip = 0;
            if (Request.UrlReferrer != null)
            {
                int.TryParse(Request.UrlReferrer.Segments.Last(), out skip);
            }
            return Math.Max(skip, 0);
        }

        private int GetCurrentSkip()
        {
            var skip = 0;
            if(Request.Url != null)
            {

Solbakken/Controllers/HomeController.cs
using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using CodeFirstMembershipSharp;
using Solbakken.Util;

namespace Solbakken.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly DataContext _db = new DataContext();

        [AllowAnonymous]
        public ActionResult Index(int? albumId)
        {
            var albumer = _db.Albums.ToList();
            ViewBag.Album = albumer;
            var thumbnails = albumer.Select(album => _db.Bilder.FirstOrDefault(x => x.AlbumId == album.Id)).Where(pic => pic != null).ToList();
            ViewBag.Thumbnails = thumbnails;
            return View();
        }

        public ActionResult Album(int albumId)
        {
            var albumer = _db.Albums.ToList();
            ViewBag.Album = albumer;
            var thumbnails = albumer.Select(album => _db.Bilder.FirstOrDefault(x => x.AlbumId == album.Id)).Where(pic => pic != null).ToList();
            ViewBag.Thumbnails = thumbnails;
            var bilder = _db.Bilder.Where(x => x.AlbumId == albumId).ToList();
            return View(bilder);
        }

        public ActionResult GetImage(int id)
        {
            var bilde = _db.Bilder.Find(id);
            return File(bilde.BildeStream, ImageUtil.GetImageContentType(bilde.Format));
        }

        public ActionResult GetThumbnail(int id)
        {
            var thumbnail = _db.Bilder.Find(id);
            return File(thumbnail.Thumbnail, ImageUtil.GetImageContentType(thumbnail.Format));
        }
       
        public ActionResult Test()
        {
            return View();
        }

        public JsonResult UploadTest(string filename)
        {
            return Json(string.Format("Added {0}", filename));
        }

        public static void CopyStream(Stream input, ref MemoryStream output)
        {
            var buffer = new byte[3276800];
            int read;
            while ((read = input.Read(buffer, 144, buffer.Length - 144 - 47)) > 0)
            {
                output.Write(buffer, 0, read);
            }
            
        }

        public static void CopyStream(Stream input, Stream output)
        {
            var buffer = new byte[3276800];
            int len;
            while ((len = input.Read(buffer, 0, (int)input.Length)) > 0)
            {
                output.Write(buffer, 0, len);
            }
        }
    }
}

Solbakken/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin luctus tincidunt justo nec tempor. 
        Aliquam erat volutpat. Fusce facilisis ullamcorper consequat. Vestibulum non sapien lectus. Nam 
        mi augue, posuere at tempus vel, dignissim vitae nulla. Nullam at quam eu sapien mattis ultrices. 
        Quisque quis leo mi, at lobortis dolor. Nullam scelerisque facilisis placerat. Fusce a augue 
        erat, malesuada euismod dui. Duis iaculis risus id felis volutpat elementum. Fusce blandit iaculis 
        quam a cursus. Cras varius tincidunt cursus. Morbi justo eros, adipiscing ac placerat sed, posuere 
        et mi. Suspendisse vulputate viverra aliquet. Duis non enim a nibh consequat mollis ac tempor 
        lorem. Phasellus elit leo, semper eu luctus et, suscipit at lacus. In hac habitasse platea 
        dictumst. Duis dignissim justo sit amet nulla pulvinar sodales.
    </p>

    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin luctus tincidunt justo nec tempor. 
        Aliquam erat volutpat. Fusce facilisis ullamcorper consequat. Vestibulum non sapien lectus. Nam 
        mi augue, posuere at tempus vel, dignissim vitae nulla. Nullam at quam eu sapien mattis ultrices. 
        Quisque quis leo mi, at lobortis dolor. Nullam scelerisque facilisis placerat. Fusce a augue 
        erat, malesuada euismod dui. Duis iaculis risus id felis volutpat elementum. Fusce blandit iaculis 
        quam a cursus. Cras varius tincidunt cursus. Morbi justo eros, adipiscing ac placerat sed, posuere 
        et mi. Suspendisse vulputate viverra aliquet. Duis non enim a nibh consequat mollis ac tempor 
        lorem. Phasellus elit leo, semper eu luctus et, suscipit at lacus. In hac habitasse platea 
        dictumst. Duis dignissim justo sit amet nulla pulvinar sodales.
    </p>

    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin luctus tincidunt justo nec tempor. 
        Aliquam erat volutpat. Fusce facilisis ullamcorper consequat. Vestibulum non sapien lectus. Nam 
        mi augue, posuere at tempus vel, dignissim vitae nulla. Nullam at quam eu sapien mattis ultrices. 
        Quisque quis leo mi, at lobortis dolor. Nullam scelerisque facilisis placerat. Fusce a augue 
        erat, malesuada euismod dui. Duis iaculis risus id felis volutpat elementum. Fusce blandit iaculis 
        quam a cursus. Cras varius tincidunt cursus. Morbi justo eros, adipiscing ac placerat sed, posuere 
        et mi. Suspendisse vulputate viverra aliquet. Duis non enim a nibh consequat mollis ac tempor 
        lorem. Phasellus elit leo, semper eu luctus et, suscipit at lacus. In hac habitasse platea 
        dictumst. Duis dignissim justo sit amet nulla pulvinar sodales.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Fusce facilisis ullamcorper consequat. Vestibulum non sapien lectus. Nam 
        mi augue, posuere at tempus vel, dignissim vitae nulla.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

Solbakken/Views/Home/Album.cshtml
@using Solbakken.Models
@model List<Bilde>

@{
    ViewBag.Title = "Bilder";
    var counter = 0;
    var albums = (List<Album>) ViewBag.Album;
    var thumbnails = (List<Bilde>) ViewBag.Thumbnails;
}
<link rel="stylesheet" type="text/css" href="~/Content/wow/style.css"/>
<script>
     $(function () {
        $.blockUI({ message: "Vær snill og vent. Laster " + @Model.Count + " bilder..."  });
    });
</script>
<div id="wowslider-container1">
    <div class="ws_images">
        <ul>
            @foreach(var bilde in Model)
            {
                <li><img src="/Home/GetImage?id=@(bilde.Id)" alt="@bilde.Beskrivelse" title="@bilde.Beskrivelse" id="wows@(counter++)"/></li>
            }
        </ul>
    </div>
@*
    <div class="ws_bullets">
        <div>
            @{var thumbCounter = 0;}
            @foreach(var bilde in Model)
            {
                <a href="#" title="@bilde.Beskrivelse"><img style="height: 100px;" src="/Home/GetThumbnail/?id=@bilde.Id" alt="@bilde.Beskrivelse"/>@(thumbCounter++)</a>
            }
        </div>
    </div>*@
</div>


<div class="page-header">
    <div class="span3">
    </div>
    <h2>Velg album</h2>
</div>
<div class="row" style="margin-left: auto; margin-right: auto; text-align: center;">
    @foreach (var album in albums)
    {
        var bilde = thumbnails.FirstOrDefault(x => x.AlbumId == album.Id);
        if (bilde == null)
        {
            continue;
        }
        @Html.Partial("_AlbumCover", bilde)
    }
</div>

<script src="~/Scripts/wow/wowslider.js"></script>
<script src="~/Scripts/wow/script.js"></script>
<script src="~/Scripts/blockui.js"></script>

<script type="text/javascript">
    function test() {
        var asdf = '<li style="position: relative; font-size: 0px; float: left;"><img id="wows1" title="frosk" alt="frosk" src="/Home/GetImage?id=21" style="position: static; visibility: visible;"></li>';
        $(".ws_images").first().find('ul').append(asdf);
        jQuery("#wowslider-container1").wowSlider({ effect: "basic", prev: "", next: "", duration: 7 * 100, delay: 15 * 100, outWidth: 640, outHeight: 480, width: 640, height: 480, autoPlay: false, stopOnHover: false, loop: false, bullets: true, caption: true, controls: true, logo: "engine1/loading.gif", images: 0 });

    }

//    $(document).ready(function () {
//        $.unblockUI();
//    });
    $(window).load(function() {
        $.unblockUI();
    });
</script>

Solbakken/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone:</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email:</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address:</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

Solbakken/Views/Home/Index.cshtml
@using Solbakken.Models
@model dynamic
@{
    ViewBag.Title = "Forside";
    var albums = (List<Album>) ViewBag.Album;
    var thumbnails = (List<Bilde>) ViewBag.Thumbnails;
}
<div class="row" style="text-align: center; margin-left: auto; margin-right: auto; display: inline-block;">
    @if (!Request.IsAuthenticated)
    {
        <div class="span2 well">
            <img src="/Images/orderedListOne.png" alt="3"/>        
            @Html.ActionLink("Registrer deg", "Register", "Account")
        </div>
        <div class="span2 well">
            <img src="/Images/orderedListTwo.png" alt="2"/>        
            @Html.ActionLink("Lag et album", "Create", "Album")
        </div>
    
        <div class="span2 well">
            <img src="/Images/orderedListThree.png" alt="3"/>        
            @Html.ActionLink("Last opp bilder", "LastOpp", "Bilde")
        </div>
        <div class="span2 well">
            <img src="/Images/orderedListFour.png" alt="1"/>
            Se på bilder
        </div>
    }
    else
    {
        <div class="span2 well">
            <img src="/Images/orderedListOne.png" alt="2"/>        
            @Html.ActionLink("Lag et album", "Create", "Album")
        </div>

        <div class="span2 well">
            <img src="/Images/orderedListTwo.png" alt="3"/>        
            @Html.ActionLink("Last opp bilder", "LastOpp", "Bilde")
        </div>
        <div class="span2 well">
            <img src="/Images/orderedListThree.png" alt="1"/>
            Se på bilder
        </div>
    }
    
    
</div>
@if(Request.IsAuthenticated)
{
    <div class="page-header">
            <div class="span3">
            </div>
            <h2>Se bilder fra album</h2>
        </div>
    <div class="row" style="margin-left: auto; margin-right: auto; text-align: center;">
        @foreach (var bilde in albums.Select(album => thumbnails.FirstOrDefault(x => x.AlbumId == album.Id)).Where(bilde => bilde != null))
        {
            @Html.Partial("_AlbumCover", bilde)
        }
    </div>
}

Solbakken/Views/Home/Test.cshtml
@model dynamic

@{
    ViewBag.Title = "Test";
}

<div id="fileList"></div>

<input id="filesToUpload" type="file" multiple="multiple"/>
<input type="button" onclick="showFiles()" value="trykk"/>

<script>

    function test2() {
        $.each($('#filesToUpload')[0].files, function (i, file) {
            var data = new FormData();
            data.append('', file);
            $.ajax({
                url: '/Home/UploadTest?filename=' + file.name,
                data: data,
                async: false,
                cache: false,
                contentType: 'multipart/form-data',
                processData: false,
                type: 'POST',
                success: function (results) {
                    $("#fileList").append(results);
                }
            });
        });
    }

    function showFiles() {
        var input = document.getElementById('filesToUpload');
        for (var x = 0; x < input.files.length; x++) {
            $.ajax({
                url: '/Home/UploadTest?filename=' + input.files[x].name,
                data: input.files[x],
                cache: false,
                async: false,
                contentType: 'multipart/form-data',
                processData: false,
                type: 'POST',
                success: function (results) {
                    $("#fileList").append(results);
                }
            });
        }
    }

</script>